### ISSUE TITLE
Exception throw when running mvn on /hangouts-chat-samples/java/card-bot

### ISSUE THREAD

**Issue by slevi2103** [gsuitedevs/hangouts-chat-samples#4]
```
[INFO] MultiException[java.lang.RuntimeException: Error scanning entry module-info.class from jar file://projects/hangouts-chat-samples/java/card-bot/target/card-bot-java-1.0-SNAPSHOT/WEB-INF/lib/javax.json-api-1.1.2.jar, java.lang.RuntimeException: Error scanning entry module-info.class from jar file://projects/hangouts-chat-samples/java/card-bot/target/card-bot-java-1.0-SNAPSHOT/WEB-INF/lib/javax.json-1.1.2.jar]`

`INFO] 	|Caused by:
[INFO] 	|java.lang.IllegalArgumentException
[INFO] 	|	at org.objectweb.asm.ClassReader.<init>(Unknown Source)
[INFO] 	|	at org.objectweb.asm.ClassReader.<init>(Unknown Source)
[INFO] 	|	at org.objectweb.asm.ClassReader.<init>(Unknown Source)
[INFO] 	|	at org.eclipse.jetty.annotations.AnnotationParser.scanClass(AnnotationParser.java:977)
[INFO] 	|	at org.eclipse.jetty.annotations.AnnotationParser.parseJarEntry(AnnotationParser.java:958)
[INFO] 	|	at org.eclipse.jetty.annotations.AnnotationParser.parseJar(AnnotationParser.java:902)
[INFO] 	|	at org.eclipse.jetty.annotations.AnnotationParser.parse(AnnotationParser.java:851)
[INFO] 	|	at org.eclipse.jetty.annotations.AnnotationConfiguration$ParserTask.call(AnnotationConfiguration.java:163)
[INFO] 	|	at org.eclipse.jetty.annotations.AnnotationConfiguration$1.run(AnnotationConfiguration.java:546)
[INFO] 	|	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:671)
[INFO] 	|	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:589)
[INFO] 	|	at java.lang.Thread.run(Thread.java:745)
[INFO] Caused by:
[INFO] java.lang.RuntimeException: Error scanning entry module-info.class from jar file:///projects/hangouts-chat-samples/java/card-bot/target/card-bot-java-1.0-SNAPSHOT/WEB-INF/lib/javax.json-api-1.1.2.jar
[INFO] 	at org.eclipse.jetty.annotations.AnnotationParser.parseJar(AnnotationParser.java:906)
[INFO] 	at org.eclipse.jetty.annotations.AnnotationParser.parse(AnnotationParser.java:851)
[INFO] 	at org.eclipse.jetty.annotations.AnnotationConfiguration$ParserTask.call(AnnotationConfiguration.java:163)
[INFO] 	at org.eclipse.jetty.annotations.AnnotationConfiguration$1.run(AnnotationConfiguration.java:546)
[INFO] 	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:671)
[INFO] 	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:589)
[INFO] 	at java.lang.Thread.run(Thread.java:745)
[INFO] Caused by:
[INFO] java.lang.IllegalArgumentException
[INFO] 	at org.objectweb.asm.ClassReader.<init>(Unknown Source)
[INFO] 	at org.objectweb.asm.ClassReader.<init>(Unknown Source)
[INFO] 	at org.objectweb.asm.ClassReader.<init>(Unknown Source)
[INFO] 	at org.eclipse.jetty.annotations.AnnotationParser.scanClass(AnnotationParser.java:977)
[INFO] 	at org.eclipse.jetty.annotations.AnnotationParser.parseJarEntry(AnnotationParser.java:958)
[INFO] 	at org.eclipse.jetty.annotations.AnnotationParser.parseJar(AnnotationParser.java:902)
[INFO] 	at org.eclipse.jetty.annotations.AnnotationParser.parse(AnnotationParser.java:851)
[INFO] 	at org.eclipse.jetty.annotations.AnnotationConfiguration$ParserTask.call(AnnotationConfiguration.java:163)
[INFO] 	at org.eclipse.jetty.annotations.AnnotationConfiguration$1.run(AnnotationConfiguration.java:546)
[INFO] 	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:671)
[INFO] 	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:589)
[INFO] 	at java.lang.Thread.run(Thread.java:745)
[INFO] 2018-03-26 00:12:33.984:INFO:oejs.AbstractC
```

Therefore, the server refused to start and http://localhost/bot return 503.

**Comment by grant** [comment]
Looks like a Runtime exception for `hangouts-chat-samples/java/card-bot`.
Can you provide more information about what Java version you're running?

**Comment by erickoledadevrel** [comment]
Closing due to inactivity.
